# Generated by Django 5.1.1 on 2024-09-14 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoraInicio', models.DateTimeField()),
                ('HoraFinal', models.DateTimeField(blank=True)),
                ('HoraReserva', models.DateTimeField(blank=True)),
                ('Cliente', models.ForeignKey(db_column='IdCliente', on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
            ],
        ),
    ]
