# Generated by Django 5.1.1 on 2024-09-14 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ClienteEspacio', '0001_initial'),
        ('Espacio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteespacio',
            name='Espacio',
            field=models.ForeignKey(db_column='IdEspacio', on_delete=django.db.models.deletion.CASCADE, to='Espacio.espacio'),
        ),
    ]
