# Generated by Django 5.1.1 on 2024-09-14 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Estacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.CharField(max_length=8)),
                ('Estado', models.BooleanField(default=False)),
                ('CostoHora', models.IntegerField(default=1)),
                ('CostoReservaHora', models.IntegerField(default=1)),
                ('Estacionamiento', models.ForeignKey(db_column='IdEstacionamiento', on_delete=django.db.models.deletion.CASCADE, to='Estacionamiento.estacionamiento')),
            ],
        ),
    ]
