# Generated by Django 5.1.1 on 2024-09-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estacionamiento', '0002_alter_estacionamiento_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='CoordenadaX',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='CoordenadaY',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
